apiVersion: v1
kind: Service
metadata:
  name: wordpress
spec:
  type: LoadBalancer
  selector:   
      role: wordpress
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http