# Deploy redis service

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: coins
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 4
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
          env:
            - name: REDIS_NAME
              value: "apolo"