# worker Service
apiVersion: v1
kind: Service
metadata:
  name: worker
  namespace: coins
spec:
  type: ClusterIP
  selector:
    app: worker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80